import { Bitter } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/components/navbar";
import FooterComponent from "@/components/footer";

const bitter = Bitter({ subsets: ["latin"] });

export const metadata = {
  title: "Aytuhan Kazandirmak",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="logo.png" type="image/png" />
      <body className={bitter.className}>
        <main className="main">
          <nav>
            <NavbarComponent />
          </nav>
          {children}
          <footer>
            <FooterComponent />
          </footer>
        </main>
      </body>
    </html>
  );
}
